### ISSUE TITLE
Disponibilizar a build compilada

### ISSUE THREAD

**Issue by fernandorech** [caelum/tubaina#47]
Olá Pessoal,

Tive muito trabalho em compilar, procurei um gradle que conseguisse compilar corretamente, instalei o pygmentize, enfim, eu tenho a build e basta instalar o pygmentize para funcionar, se for ok eu posso disponibilizar.

Abraços

**Comment by csokol** [comment]
Opa, seria legal sim.

Só pra avisar, criei um dockerfile pra fazer todo o trabalho também:
https://github.com/caelum/tubaina/blob/master/src/docker/tubaina/Dockerfile

Talvez fosse uma boa documentar que ele existe e como usa-lo, acho que
cheguei até a puxar no dockerhub.

**Comment by fernandorech** [comment]
Muito bom esse dockerfile, nem sabia que existia, seria interessante colocar no readme do projeto porque agilizaria quem fosse usar.

**Comment by rponte** [comment]
Bacana, Sokol! Ainda não brinquei com Docker!

Aqui na empresa nós rodamos o Tubaina numa VM com Vagrant com Ubuntu, assim
fica fácil configurá-lo em qualquer OS! Para configurar a máquina nós
usamos este script para provisionar a VM:
https://gist.github.com/rponte/6251800

Um abraço!

2015-02-03 14:47 GMT-03:00 csokol <notifications@github.com>:

> Opa, seria legal sim.
>
> Só pra avisar, criei um dockerfile pra fazer todo o trabalho também:
> https://github.com/caelum/tubaina/blob/master/src/docker/tubaina/Dockerfile
>
> Talvez fosse uma boa documentar que ele existe e como usa-lo, acho que
> cheguei até a puxar no dockerhub.
>
> On Tue Feb 03 2015 at 3:45:54 PM fernandorech <notifications@github.com>
> wrote:
>
> > Olá Pessoal,
> >
> > Tive muito trabalho em compilar, procurei um gradle que conseguisse
> > compilar corretamente, instalei o pygmentize, enfim, eu tenho a build e
> > basta instalar o pygmentize para funcionar, se for ok eu posso
> > disponibilizar.
> >
> > Abraços
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/caelum/tubaina/issues/47>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caelum/tubaina/issues/47#issuecomment-72698415>.
>



-- 
Rafael Ponte
TriadWorks | Formação Java
http://cursos.triadworks.com.br

**Comment by csokol** [comment]
Legal @rponte ! Se quiser colocar o Vagrantfile aqui no repositório seria legal!

@fernandorech, acabei de documentar a imagem do docker. Servir um binário das versões do projeto dá um certo trabalho, podemos ficar com essa solução por enquanto?
